apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: dusseldorf
  name: pleiepengesoknad-api-redis
  namespace: dusseldorf
  annotations:
    nais.io/read-only-file-system: "false"
    nais.io/run-as-user: "999"
spec:
  image: redis:6.2.6-alpine # or a custom Redis-image
  port: 6379
  accessPolicy:
    inbound:
      rules:
        - application: pleiepengesoknad-api
  replicas: # A single Redis-app doesn't scale
    min: 1
    max: 1
  resources: # you need to monitor need your self
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 20m
      memory: 50Mi
  service:
    port: 6379
    protocol: redis