apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  labels:
    team: dusseldorf
  name: pleiepengesoknad-api-redis
  namespace: dusseldorf
spec:
  image: redis:5-alpine # or a custom Redis-image
  port: 6379
  accessPolicy:
    inbound:
      rules:
        - application: pleiepengesoknad-api
  replicas: # A single Redis-app doesn't scale
    min: 1
    max: 1
  resources: # you need to monitor need your self
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 250m
      memory: 256Mi
  service:
    port: 6379
    protocol: redis