apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pleiepengesoknad-api
  namespace: default
  labels:
    team: {{team}}
spec:
  image: {{version}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  ingresses:
    - https://pleiepengesoknad-api-q.nav.no
    - https://pleiepengesoknad-api.nais.oera-q.local
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  vault:
    enabled: true
  webproxy: true
  env:
    - name: CORS_ADDRESSES
      value: https://pleiepengesoknad-q.nav.no
    - name: ISSUER
      value: https://login.microsoftonline.com/d38f25aa-eab8-4c50-9f28-ebf92c1256f2/v2.0/
    - name: COOKIE_NAME
      value: selvbetjening-idtoken
    - name: JWKS_URI
      value: https://login.microsoftonline.com/navtestb2c.onmicrosoft.com/discovery/v2.0/keys?p=b2c_1a_idporten_ver1
    - name: AKTOER_REGISTER_URL
      value: https://api-gw-q1.oera.no/helse-reverse-proxy/aktoer-register
    - name: SPARKEL_URL
      value: https://api-gw-q1.oera.no/helse-reverse-proxy/sparkel
    - name: TOKEN_URL
      value: https://api-gw-q1.oera.no/helse-reverse-proxy/security-token-service/rest/v1/sts/token
    - name: PLEIEPENGESOKNAD_MOTTAK_BASE_URL
      value: https://api-gw-q1.oera.no/helse-reverse-proxy/pleiepengesoknad-mottak
    - name: PLEIEPENGER_DOKUMENT_BASE_URL
      value: https://k9-dokument.nais.oera-q.local
    - name: AZURE_CLIENT_ID
      value: 1c494523-b92c-4387-9e18-a43e654d511c
    - name: AZURE_V2_DISCOVERY_ENDPOINT
      value: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration
    - name: SENDE_SOKNAD_TIL_PROSESSERING_SCOPES
      value: 8caa7c32-1523-43a7-af95-63123938f45c/.default