apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100M"
spec:
  image: {{image}}
  port: 8080
  liveness:
    path: isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  replicas:
    min: {{minReplicas}}
    max: {{maxReplicas}}
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  azure:
    application:
      enabled: true
      tenant: {{tenant}}
  accessPolicy:
    outbound:
      rules:
        - application: {{app}}-redis
        - application: k9-mellomlagring
      external:
      {{#each externalHosts as |host|}}
          - host: {{host }}
      {{/each}}
  env:
  {{#each env}}
    - name: {{@key}}
      value: {{this}}
  {{/each}}
  envFrom:
    - configmap: loginservice-idporten
    - secret: {{app}}
